project:
  type: book
  output-dir: _book
  
book:
  title: "FAQ in statistics"
  author: "Sarah Kaspar"
  description: | 
    Frequently asked questions explained in short stand-alone articles.
  #cover-image: images/cover.png
  site-url: https://tutorials.thecoatlessprofessor.com/quarto-book-template
  repo-url: https://github.com/coatless-tutorials/quarto-book-template
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: hypothesis-tests.qmd
      chapters: 
        - Wilcoxon.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true
